## Bin file to CSV file

In [40]:
import numpy as np
import pandas as pd

magic, seq = [], []
x_acc, y_acc, z_acc = [], [], []
roll, patch, yaw = [], [], []
sound, loadcell, pressure, pos_cmd, pos_fdb = [], [], [], [], []
limit_sw, temp, humid, dev_err, rms = [], [], [], [], []

# columns = [magic, seq, x_acc, y_acc, z_acc, roll, patch, yaw, sound, loadcell, pressure, pos_cmd, pos_fdb, limit_sw, temp, humid, dev_err, rms]

with open('20200825-1-Header.bin','r', errors='ignore') as f:
    '''
    ndarray 데이터 형태 지정: https://rfriend.tistory.com/tag/dtype
    
    '''
    for _ in range(11906): # len(bin file)
        magic.append(np.fromfile(f, '<u2', 2))        # uint32, little endian
        seq.append(np.fromfile(f, '<u2', 1))          # uint16, little endian
        x_acc.append(np.fromfile(f, '<i2', 1))        # int16, little endian
        y_acc.append(np.fromfile(f, '<i2', 1))        # int16, little endian
        z_acc.append(np.fromfile(f, '<i2', 1))        # int16, little endian
        roll.append(np.fromfile(f, '<i2', 1))         # int16, little endian
        patch.append(np.fromfile(f, '<i2', 1))        # int16, little endian
        yaw.append(np.fromfile(f, '<i2', 1))          # int16, little endian
        sound.append(np.fromfile(f, '<u2', 1))        # uint16, little endian
        loadcell.append(np.fromfile(f, '<i2', 1))     # int16, little endian
        pressure.append(np.fromfile(f, '<u1', 1))     # uint8, little endian
        pos_cmd.append(np.fromfile(f, '<u1', 1))      # uint8, little endian
        pos_fdb.append(np.fromfile(f, '<u1', 1))      # uint8, little endian
        limit_sw.append(np.fromfile(f, '<u1', 1))     # uint8, little endian
        temp.append(np.fromfile(f, '<i1', 1))         # int8, little endian
        humid.append(np.fromfile(f, '<u1', 1))        # uint8, little endian
        dev_err.append(np.fromfile(f, '<u2', 1))      # uint16, little endian
        rms.append(np.fromfile(f, '<u2', 1))          # uint16, little endian

47628


### list to numpy array & reshape array

In [17]:
seq = np.array(seq).reshape(-1, )
x_acc = np.array(x_acc).reshape(-1, )
y_acc = np.array(y_acc).reshape(-1, )
z_acc = np.array(z_acc).reshape(-1, )
roll = np.array(roll).reshape(-1, )
patch = np.array(patch).reshape(-1, )
yaw = np.array(yaw).reshape(-1, )
sound = np.array(sound).reshape(-1, )
loadcell = np.array(loadcell).reshape(-1, )
pressure = np.array(pressure).reshape(-1, )
pos_cmd = np.array(pos_cmd).reshape(-1, )
pos_fdb = np.array(pos_fdb).reshape(-1, )
limit_sw = np.array(limit_sw).reshape(-1, )
temp = np.array(temp).reshape(-1, )
humid = np.array(humid).reshape(-1, )
dev_err = np.array(dev_err).reshape(-1, )
rms = np.array(rms).reshape(-1, )

### check array

In [22]:
print(seq)
print(x_acc)
print(y_acc)
print(z_acc)
print(roll)
print(patch)
print(yaw)
print(sound)
print(loadcell)
print(pressure)
print(pos_cmd)
print(pos_fdb)
print(limit_sw)
print(temp)
print(humid)
print(dev_err)
print(rms)

[21943 21944 21945 ... 33846 33847 33848]
[-2 12 12 ... -8 38 -2]
[ 56  32  18 ...  66 108  44]
[4058 4116 4066 ... 4084 3998 4092]
[-34 -34 -37 ... -43 -38 -34]
[ -6  -8  -7 ... -12 -15 -13]
[11  9  6 ...  8 11  9]
[530 530 530 ... 544 544 544]
[1 1 1 ... 1 1 1]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[3 3 3 ... 3 3 3]
[38 38 38 ... 37 37 37]
[29 29 29 ... 29 29 29]
[ 0 16  0 ...  4  0  0]
[264 263 265 ... 266 265 261]


### concat array and transpose

In [23]:
data = np.array([seq, x_acc, y_acc, z_acc,
                 roll, patch, yaw,
                 sound, loadcell, pressure, pos_cmd, pos_fdb,
                 limit_sw, temp, humid, dev_err, rms])
data = data.T
data

array([[21943,    -2,    56, ...,    29,     0,   264],
       [21944,    12,    32, ...,    29,    16,   263],
       [21945,    12,    18, ...,    29,     0,   265],
       ...,
       [33846,    -8,    66, ...,    29,     4,   266],
       [33847,    38,   108, ...,    29,     0,   265],
       [33848,    -2,    44, ...,    29,     0,   261]], dtype=int32)

### make array to dataframe

In [42]:
columns = ['seq', 'x_acc', 'y_acc', 'z_acc', 
           'roll', 'patch', 'yaw', 
           'sound', 'loadcell', 'pressure', 'pos_cmd', 'pos_fdb', 
           'limit_sw', 'temp', 'humid', 'dev_err', 'rms']

df = pd.DataFrame(data = data,
                  columns = columns)
df

seq  x_acc  y_acc  z_acc  roll  patch  yaw  sound  loadcell  \
0      21943     -2     56   4058   -34     -6   11    530         1   
1      21944     12     32   4116   -34     -8    9    530         1   
2      21945     12     18   4066   -37     -7    6    530         1   
3      21946      8     32   4058   -39     -9    6    530         1   
4      21947     36     36   4062   -40    -14    5    530         1   
...      ...    ...    ...    ...   ...    ...  ...    ...       ...   
11901  33844    -12     56   4124   -42     -6    7    546         1   
11902  33845     44     72   4088   -32     -9    6    544         1   
11903  33846     -8     66   4084   -43    -12    8    544         1   
11904  33847     38    108   3998   -38    -15   11    544         1   
11905  33848     -2     44   4092   -34    -13    9    544         1   

       pressure  pos_cmd  pos_fdb  limit_sw  temp  humid  dev_err  rms  
0             0        0        0         3    38     29        0  264  
1             0        0        0         3    38     29       16  263  
2             0        0        0         3    38     29        0  265  
3             0        0        0         3    38     29       16  264  
4             0        0        0         3    38     29        4  264  
...         ...      ...      ...       ...   ...    ...      ...  ...  
11901         0        0        0         3    37     29       64  267  
11902         0        0        0         3    37     29       16  261  
11903         0        0        0         3    37     29        4  266  
11904         0        0        0         3    37     29        0  265  
11905         0        0        0         3    37     29        0  261  

[11906 rows x 17 columns]

In [43]:
df.to_csv('bin2csvfile.csv',
          index=False)